CREATE TABLE public.form (
                      id BIGINT generated BY DEFAULT AS IDENTITY,
                      userurl text NOT NULL,
                      newurl text NOT NULL,
                      CONSTRAINT form_id_pkey PRIMARY KEY (id),
                      CONSTRAINT form_unique UNIQUE (newurl)
);
CREATE TABLE public.statistic (
                           id BIGINT generated BY DEFAULT AS IDENTITY,
                           ip text NOT NULL,
                           newurl_form text NOT NULL,
                           time text NOT NULL,
                           CONSTRAINT statistic_id_pkey PRIMARY KEY (id)

);